### cài đặt extension REST Client extension
### Lấy tất cả hợp đồng
GET http://localhost:3000/hopdong

### Tạo mới hợp đồng 
POST http://localhost:3000/hopdong/Create
Content-Type: application/json

{
  "MaHD": "HD07",
  "MaPhong": "P102",
  "NgayBD": "2025-07-01",
  "NgayKT": "2025-12-31",
  "MaSV": "SV01",
  "MaNV": "nhanvien11"
}

### Cập nhật hợp đồng
PUT http://localhost:3000/hopdong/HD07
Content-Type: application/json

{
  "NgayKT": "2025-12-31",
  "MaNV": "nhanvien11"
}

### Xóa hợp đồng
DELETE http://localhost:3000/hopdong/HD07
### Tìm kiếm hợp đồng theo keyword
GET http://localhost:3000/hopdong/search?keyword=01
